export const Types = {
  FIND_ALL_TODOS: 'FIND_ALL_TODOS',
  NEW_TODO: 'NEW_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  CHANGE_STATUS_TODO: 'CHANGE_STATUS_TODO',
  ADD_TO_QUEUE: 'ADD_TO_QUEUE',
  CLEAR_QUEUE: 'CLEAR_QUEUE',
  LOADING: 'LOADING',
  LOADED: 'LOADED',
};
